<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>ErgoSm</Authors>
    <Copyright>Egor Smirnov copyright (C)</Copyright>
    <Version>0.1.8</Version>
    <RepositoryUrl>https://github.com/ErgoSm/Calculis</RepositoryUrl>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

</Project>
