<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>$(AssemblyName)</PackageId>
    <Product>$(AssemblyName)</Product>
    <Description>Core classes of Calculis</Description>
  </PropertyGroup>

</Project>
